### ISSUE TITLE
Use `antd-phone-input` over `react-phone-input-2`

### ISSUE THREAD

**Issue by ArtyomVancyan** [open-condo-software/condo#3906]
The [`antd-phone-input`](https://github.com/ArtyomVancyan/antd-phone-input) is designed to use with Ant Design and is well maintained by me and I highly recommend using it. It is compatible with the version of `antd` you are using. I tried to open a PR with the necessary changes but could not run the workspace on the development environment (it uses huge storage and has issues with migrations or your [Getting started](https://github.com/open-condo-software/condo#getting-started) section of the README need to be updated).

Thanks for your attention.

**Comment by pahaz** [comment]
Can you contribute this changes?

**Comment by toplenboren** [comment]
Seems like this issue is stale. Setting up repo should be far more simple now

Closing the issue
