### ISSUE TITLE
Domain hardcode

### ISSUE THREAD

**Issue by paulo-rossy** [open-condo-software/condo#4731]
Hi. I'm trying to adopt your project to ES language.

At the moment your translations have a hardcoded `doma.ai` name.

Can you mode it to some config? or use something like `{{ SITE_NAME }}` or something similar for that?

At the moment I've created a custom translation loader function with replace logic. I've replace everything related to `doma.ai`. But it looks a little hacky.

**Comment by sitozzz** [comment]
Hi there, that's good suggestion. I suppose we'll do this in one of the upcoming releases

> Hi. I'm trying to adopt your project to ES language.
> 
> At the moment your translations have a hardcoded `doma.ai` name.
> 
> Can you mode it to some config? or use something like `{{ SITE_NAME }}` or something similar for that?
> 
> At the moment I've created a custom translation loader function with replace logic. I've replace everything related to `doma.ai`. But it looks a little hacky.

Hi there! That's a good suggestion, so I think we'll do this in one of the upcoming releases

**Comment by SavelevMatthew** [comment]
Hi, please clarify, are we talking about translations? If yes, you can use a separate translation for the company name and use intl + values in the translation lines where it is present.

Something like this:
```json
{
  "company.name": "My Cool Company",
  "company.shortName": "Company",
  "company.domain": "company.com",
  "some.translation.with.company": "Thanks for visiting {companyName}!"
}
```

```js
const intl = useIntl()
const CompanyTitle = intl.formatMessage({ id: 'company.name' })
const MyMessage = intl.formatMessage({ id: 'some.translation.with.company' }, {
    companyName: CompanyTitle
})
```

https://formatjs.io/docs/react-intl/api/#formatmessage
