### ISSUE TITLE
Add Quota Field for Residents

### ISSUE THREAD

**Issue by paulo-rossy** [open-condo-software/condo#4870]
Dear Developers,

I kindly request the addition of a quota field (percentage ownership of an apartment) for residents. This parameter is crucial for property management and ownership records.

I have attached screenshots to illustrate this requirement. I can also submit a pull request with the necessary changes.

Thank you for considering this feature.
![Frame 513873](https://github.com/open-condo-software/condo/assets/165659722/806936f9-de8c-4c68-9d95-c82f3a2b2fc9)

**Comment by toplenboren** [comment]
Hi! 

We have added Quota field for Contact model, it is non-required decimal field

Is this change aligned with your use case? :-)
