### ISSUE TITLE
Differences between condo and open-condo-platform

### ISSUE THREAD

**Issue by EmilioRusso77** [open-condo-software/condo#4969]
Hi all, 
First of all I want to congratulate you on this splendid project. I would like to use this application to manage my condominium, given that I am a computer scientist and Java developer, I was wondering what differences there are between the two repos. It would be appropriate to add some more information on Git. Greetings Emilio

**Comment by toplenboren** [comment]
Hi! Thank you for your kind words :-) 

In a nutshell, `open-condo-software` is a copy of `condo` without some private code. So from a technical point of view, they are same-ish

From a business point of view, however: 
- `open-condo-software` will stay open source in the future
- `condo` might be switched to close source in the future, but as of now we are not considering this

**Comment by EmilioRusso77** [comment]
thanks for this explanation, I tried to install open condo on a vm, I get to the command node ./bin/prepare.js:
I also installed commander with yarn install commander, but I still get the same error: Error: Cannot find module 'commander', but I noticed in the yarn logs that there is another problem with @keystonejs-app-admin-ui- npm.
errors:
yarn install: :➤ YN0001: │ Error: @keystonejs/app-admin-ui@patch:@keystonejs/app-admin-ui@npm:7.5.2#.yarn/patches/@keystonejs-app-admin-ui-npm-7.5.2-ada8bd01c3.patch::locator=root%40workspace%3A.:
 ENOENT: no such file or directory, open '/home/emilio/Desktop/Condominium/condo/.yarn/patches/@keystonejs-app-admin-ui-npm-7.5.2-ada8bd01c3.patch'


# 4) create databases for all apps and apps/.env files
node ./bin/prepare.js
emilio@emilio-VirtualBox:~/Desktop/Condominium/condo$ node ./bin/prepare.js
node:internal/modules/cjs/loader:1031
  throw err;
  ^

Error: Cannot find module 'commander'
Require stack:
- /home/emilio/Desktop/Condominium/condo/bin/prepare.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/emilio/Desktop/Condominium/condo/bin/prepare.js:3:21)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/emilio/Desktop/Condominium/condo/bin/prepare.js' ]
}

**Comment by toplenboren** [comment]
Hey, can you please check out this thread? Seems a lot like your case (commander):

https://github.com/open-condo-software/condo/issues/4899

**Comment by EmilioRusso77** [comment]
I tried following the advice https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install 1315, but the result doesn't change:

![image](https://github.com/user-attachments/assets/9ab1ddf1-4fd9-4d7c-a72c-296e06353491)

**Comment by toplenboren** [comment]
Hi, I'm closing this issue, since original question has been answered for. 

About the issue with commander – you can check out repo now, we did some stuff to make installation easier 🙌
