### ISSUE TITLE
Cant Login

### ISSUE THREAD

**Issue by cogeni** [open-condo-software/condo#5123]
Dont see the information to login in the env only this 

COOKIE_SECRET=condo-secret
DATABASE_URL=postgresql://postgres:postgres@127.0.0.1/local-condo
REDIS_URL=redis://127.0.0.1:6379/6
PORT=4006
SPORT=8006
SERVER_URL=http://localhost:4006

**Comment by cogeni** [comment]
I got the file but looks like only the mobile 4006 working

**Comment by pahaz** [comment]
Could you please frovide a full console log of your `prepare` process
