### ISSUE TITLE
Duplicate Document Names Overwrite Each Other on Property Documents Tab

### ISSUE THREAD

**Issue by paulo-rossy** [open-condo-software/condo#5446]
### Bug: Duplicate Document Names Overwrite Each Other on Property Documents Tab

**Description:**

When adding documents on the "Property" tab (`<baseUrl>/property/<propertyId>`), files with identical names overwrite each other, leading to unexpected behavior and 500 error.

**Reproduction Cases:**

1. **Adding two documents with the same name:**
   - **Steps:**
     1. Upload a document with a specific name (e.g., "document.pdf").
     2. Upload another document with the same name.
     3. Delete the second document.
   - **Result:** When attempting to download the first document, the user is redirected to `<baseUrl>/api/files/document/<documentName>`, which returns a 500 error.

2. **Adding documents with the same name in different properties:**
   - **Steps:**
     1. Upload a document with a specific name (e.g., "document.pdf") to one property.
     2. Upload a different document with the same name to another property.
   - **Result:** The file is overwritten, causing one document to replace the other, despite them being associated with different properties.
   - **Issue:** If the document is deleted in one property, it still appears in the other, but navigating to it leads to a 500 error.

**Proposed Solution:**

To prevent overwriting, append the property address to the document's file name upon upload, ensuring unique identifiers for each file.

---

Thank you for looking into this issue!

**Comment by toplenboren** [comment]
Hi, seems like we have fixed it in one of recent patches
